sudo: required
language: java
jdk:
 - oraclejdk8
services:
 - docker
before_install:
  - curl -L https://get.pulumi.com/ | bash -s -- --version 0.17.1
  - export PATH=$PATH:$HOME/.pulumi/bin
  - chmod +x scripts/travis_pull_request.sh
  - chmod +x scripts/travis_push.sh
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
 - pip install --user awscli
 - eval $(aws ecr get-login --no-include-email --region us-east-1)
 - ./gradlew clean bootJar
 - docker build -t bpm-people-api:latest .
 - docker tag bpm-people-api:latest 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-people-api:$TRAVIS_BUILD_ID
 - docker push 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-people-api:$TRAVIS_BUILD_ID
 - docker tag bpm-people-api:latest 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-people-api:latest
 - docker push 524819651720.dkr.ecr.us-east-1.amazonaws.com/bpm-people-api:latest
 - ./scripts/travis_push.sh
 - ./scripts/travis_pull_request.sh
addons:
  sonarcloud:
    organization: 'ioet'
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - sonar-scanner