package com.ioet.bpm.people.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import java.util.Date;

/**
 * This model allows saved all the data of the authentications from a user either by facebook or google
 */
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "people_auth_history")
public class AuthHistory extends AuditLog {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String personId;

    @NotBlank
    @DynamoDBAttribute
    private String accessToken;

    @NotBlank
    @DynamoDBAttribute
    private String tokenType;

    @NotBlank
    @DynamoDBAttribute
    private Date start;

    @NotBlank
    @DynamoDBAttribute
    private Date expiresIn;

    @NotBlank
    @DynamoDBAttribute
    private String provider;
}
